# Suas chaves do Supabase
SUPABASE_URL = "https://gddseopytaabdxmgubzc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZHNlb3B5dGFhYmR4bWd1YnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMTY5NjEsImV4cCI6MjA4NDY5Mjk2MX0.AUt6QqEBC2MRCnKwBYILCvrKGFttmL3iUi6FkPKWgo0"

# --- ADICIONE O TOKEN AQUI (FORA DE GRUPOS) ---
MP_ACCESS_TOKEN = "APP_USR-7913434359941227-021020-df970856113428c3f717e569979b5b10-86921969"

# Suas chaves do Strava
STRAVA_CLIENT_ID = "197487"
STRAVA_CLIENT_SECRET = "2d7e380d8348b5ea2a8e4adf64fdcd69b2ef116f"
REDIRECT_URI = "http://192.168.1.13:8501"

# Configurações do Twilio
[twilio]
TWILIO_SID = "ACa4021ac5afa057dcfcfdd0126fbfaa2e"
TWILIO_TOKEN = "18ee37a12b39555c915fcfe3f914390e"
TWILIO_PHONE_NUMBER = "14155238886"
MEU_CELULAR = "5511969603611"