SUPABASE_URL = "https://gddseopytaabdxmgubzc.supabase.co"
SUPABASE_KEY = "sb_secret_vvXs87TVvu0tanG_I4ufqA_FotB2J_3"

# Grupo Mercado Pago
[mercadopago]
MP_ACCESS_TOKEN = "APP_USR-7913434359941227-021020-df970856113428c3f717e569979b5b10-86921969"

# Grupo Strava
[strava]
STRAVA_CLIENT_ID = "197487"
STRAVA_CLIENT_SECRET = "2d7e380d8348b5ea2a8e4adf64fdcd69b2ef116f"
REDIRECT_URI = "http://192.168.1.13:8501"
STRAVA_VERIFY_TOKEN = "fabiostrava2026"

# Grupo Twilio
[twilio]
TWILIO_SID = "ACa4021ac5afa057dcfcfdd0126fbfaa2e"
TWILIO_TOKEN = "e55dbc1b28da6819c1b95939da90ed46"
TWILIO_PHONE_NUMBER = "16507284304"
MEU_CELULAR = "5511969603611"